# Generated by Django 4.1.5 on 2023-01-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='profile',
            name='git_profile',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Git link'),
        ),
    ]
