# Generated by Django 4.1.5 on 2023-01-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_remove_profile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='git_profile',
            field=models.URLField(blank=True, null=True, verbose_name='Git link'),
        ),
    ]
