# Generated by Django 4.1.5 on 2023-01-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_type_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('add_project_user', 'Add project user'), ('delete_project_user', 'Delete project user')], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
