# Generated by Django 4.1.5 on 2023-01-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('add_project_user', 'Add project user'), ('delete_project_user', 'Delete project user'), ('view_list_of_users', 'View list of users')], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
